// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpraApi.Data;

#nullable disable

namespace SimpraApi.Data.Migrations
{
    [DbContext(typeof(SimpraDbContext))]
    [Migration("20230511185419_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpraApi.Domain.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Province")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LastName", "Country");

                    b.ToTable("Staff", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "Apt. 548",
                            City = "Stoltenbergside",
                            Country = "Suriname",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 185, DateTimeKind.Utc).AddTicks(7322),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1957, 9, 8, 15, 30, 4, 457, DateTimeKind.Local).AddTicks(5211),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "roxanne.runolfsson21@gmail.com",
                            FirstName = "Roxanne",
                            LastName = "Runolfsson",
                            Phone = "69019880565",
                            Province = "Illinois",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "Suite 860",
                            City = "Royceside",
                            Country = "Spain",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 185, DateTimeKind.Utc).AddTicks(9801),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1991, 5, 29, 23, 41, 57, 662, DateTimeKind.Local).AddTicks(2693),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "spencer.block@hotmail.com",
                            FirstName = "Spencer",
                            LastName = "Block",
                            Phone = "42130698756",
                            Province = "Indiana",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "Suite 849",
                            City = "Lake Alainaville",
                            Country = "Senegal",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(921),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1968, 9, 15, 13, 32, 14, 347, DateTimeKind.Local).AddTicks(9299),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "virgil.skiles@gmail.com",
                            FirstName = "Virgil",
                            LastName = "Skiles",
                            Phone = "64560676037",
                            Province = "Nebraska",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "Suite 779",
                            City = "Greenfelderside",
                            Country = "French Polynesia",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(1910),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1979, 3, 22, 9, 47, 34, 22, DateTimeKind.Local).AddTicks(1727),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "theresa5@yahoo.com",
                            FirstName = "Theresa",
                            LastName = "Lang",
                            Phone = "08000068143",
                            Province = "Idaho",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "Apt. 432",
                            City = "West Zoila",
                            Country = "Mexico",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(2870),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1978, 3, 20, 8, 27, 37, 25, DateTimeKind.Local).AddTicks(309),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "willie.abernathy@yahoo.com",
                            FirstName = "Willie",
                            LastName = "Abernathy",
                            Phone = "19108558830",
                            Province = "Hawaii",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AddressLine = "Apt. 948",
                            City = "New Dulce",
                            Country = "Bhutan",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(3873),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(2002, 5, 30, 10, 39, 35, 38, DateTimeKind.Local).AddTicks(7320),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "judy.weimann74@yahoo.com",
                            FirstName = "Judy",
                            LastName = "Weimann",
                            Phone = "12590757150",
                            Province = "South Carolina",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AddressLine = "Apt. 290",
                            City = "Schinnerton",
                            Country = "British Indian Ocean",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(4827),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1991, 6, 26, 2, 33, 39, 42, DateTimeKind.Local).AddTicks(4829),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vickie11@yahoo.com",
                            FirstName = "Vickie",
                            LastName = "Heidenreich",
                            Phone = "29296417177",
                            Province = "Massachusetts",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AddressLine = "Apt. 444",
                            City = "New Chasefurt",
                            Country = "Solomon Islands",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(5787),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1976, 3, 12, 19, 33, 52, 354, DateTimeKind.Local).AddTicks(5438),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emilio.carter84@gmail.com",
                            FirstName = "Emilio",
                            LastName = "Carter",
                            Phone = "95125652570",
                            Province = "Missouri",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AddressLine = "Apt. 439",
                            City = "South Jarenmouth",
                            Country = "Sao Tome and Princip",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(6742),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1982, 8, 27, 0, 37, 0, 7, DateTimeKind.Local).AddTicks(2317),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vicki.green57@hotmail.com",
                            FirstName = "Vicki",
                            LastName = "Green",
                            Phone = "95804034622",
                            Province = "Wisconsin",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AddressLine = "Suite 253",
                            City = "Mireyafurt",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(7647),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1954, 6, 7, 5, 10, 51, 970, DateTimeKind.Local).AddTicks(1463),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "clarence.rath@gmail.com",
                            FirstName = "Clarence",
                            LastName = "Rath",
                            Phone = "50105240531",
                            Province = "New York",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AddressLine = "Suite 752",
                            City = "Smithamhaven",
                            Country = "Iran",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(8508),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1971, 4, 7, 23, 20, 37, 949, DateTimeKind.Local).AddTicks(4954),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "betty69@yahoo.com",
                            FirstName = "Betty",
                            LastName = "Sanford",
                            Phone = "25296144051",
                            Province = "Iowa",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AddressLine = "Apt. 228",
                            City = "Alexannemouth",
                            Country = "Guatemala",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 186, DateTimeKind.Utc).AddTicks(9385),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1971, 6, 16, 5, 26, 12, 271, DateTimeKind.Local).AddTicks(9173),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "guillermo.mayert68@yahoo.com",
                            FirstName = "Guillermo",
                            LastName = "Mayert",
                            Phone = "58555758445",
                            Province = "North Dakota",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AddressLine = "Apt. 231",
                            City = "South Frederique",
                            Country = "Samoa",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(449),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1980, 12, 23, 9, 11, 18, 900, DateTimeKind.Local).AddTicks(418),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marion_boehm22@yahoo.com",
                            FirstName = "Marion",
                            LastName = "Boehm",
                            Phone = "60725877760",
                            Province = "Iowa",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AddressLine = "Suite 201",
                            City = "Shanahaven",
                            Country = "Chile",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(1363),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1962, 10, 26, 4, 35, 47, 419, DateTimeKind.Local).AddTicks(7251),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eloise15@yahoo.com",
                            FirstName = "Eloise",
                            LastName = "Morar",
                            Phone = "32440683981",
                            Province = "Nevada",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AddressLine = "Apt. 943",
                            City = "Gerryfort",
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(2277),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1983, 12, 2, 15, 21, 44, 24, DateTimeKind.Local).AddTicks(8243),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "terrell.erdman42@yahoo.com",
                            FirstName = "Terrell",
                            LastName = "Erdman",
                            Phone = "18519570144",
                            Province = "Mississippi",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AddressLine = "Apt. 812",
                            City = "West Dashawnton",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(3186),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1975, 1, 3, 16, 5, 21, 379, DateTimeKind.Local).AddTicks(1593),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia88@yahoo.com",
                            FirstName = "Patricia",
                            LastName = "Wilkinson",
                            Phone = "87326366335",
                            Province = "Rhode Island",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AddressLine = "Suite 670",
                            City = "Lake Jordane",
                            Country = "Bahrain",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(4148),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1954, 7, 30, 10, 23, 26, 731, DateTimeKind.Local).AddTicks(8166),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "agnes_damore@gmail.com",
                            FirstName = "Agnes",
                            LastName = "D'Amore",
                            Phone = "06720046475",
                            Province = "Missouri",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AddressLine = "Suite 832",
                            City = "East Creolamouth",
                            Country = "Haiti",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(5174),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1964, 3, 22, 1, 56, 4, 288, DateTimeKind.Local).AddTicks(4048),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert23@hotmail.com",
                            FirstName = "Robert",
                            LastName = "Jaskolski",
                            Phone = "03027608512",
                            Province = "Alabama",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AddressLine = "Suite 687",
                            City = "West Stephanietown",
                            Country = "Singapore",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(6233),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1986, 2, 17, 19, 9, 2, 48, DateTimeKind.Local).AddTicks(9001),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "domingo_schumm@gmail.com",
                            FirstName = "Domingo",
                            LastName = "Schumm",
                            Phone = "67360682377",
                            Province = "New Jersey",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AddressLine = "Suite 858",
                            City = "New Zack",
                            Country = "Saint Helena",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(7228),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1969, 3, 10, 15, 38, 7, 830, DateTimeKind.Local).AddTicks(999),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jacqueline.rempel@hotmail.com",
                            FirstName = "Jacqueline",
                            LastName = "Rempel",
                            Phone = "78519165495",
                            Province = "West Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            AddressLine = "Suite 023",
                            City = "Eastonmouth",
                            Country = "Haiti",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(8134),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1990, 11, 7, 16, 38, 46, 783, DateTimeKind.Local).AddTicks(1790),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erick95@yahoo.com",
                            FirstName = "Erick",
                            LastName = "Gulgowski",
                            Phone = "48040562786",
                            Province = "South Dakota",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            AddressLine = "Apt. 861",
                            City = "Charlestown",
                            Country = "Uzbekistan",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 187, DateTimeKind.Utc).AddTicks(9090),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1973, 12, 12, 15, 19, 41, 100, DateTimeKind.Local).AddTicks(635),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "doyle_torphy80@gmail.com",
                            FirstName = "Doyle",
                            LastName = "Torphy",
                            Phone = "99740337435",
                            Province = "Wyoming",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            AddressLine = "Suite 575",
                            City = "New Maeve",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(130),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1977, 6, 13, 9, 14, 47, 519, DateTimeKind.Local).AddTicks(6942),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "micheal3@yahoo.com",
                            FirstName = "Micheal",
                            LastName = "Cronin",
                            Phone = "99882242572",
                            Province = "South Carolina",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            AddressLine = "Apt. 772",
                            City = "South Daynashire",
                            Country = "Italy",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(1173),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1977, 2, 1, 1, 33, 46, 994, DateTimeKind.Local).AddTicks(8050),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cody83@yahoo.com",
                            FirstName = "Cody",
                            LastName = "Brakus",
                            Phone = "61479260872",
                            Province = "Washington",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            AddressLine = "Apt. 964",
                            City = "Labadiebury",
                            Country = "Bouvet Island (Bouve",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(2114),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1997, 3, 25, 23, 21, 21, 221, DateTimeKind.Local).AddTicks(994),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dianne_grant@gmail.com",
                            FirstName = "Dianne",
                            LastName = "Grant",
                            Phone = "40292861714",
                            Province = "Kentucky",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            AddressLine = "Suite 410",
                            City = "North Cathryn",
                            Country = "Tonga",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(3012),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1963, 3, 14, 23, 39, 8, 381, DateTimeKind.Local).AddTicks(4939),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kim_cartwright@hotmail.com",
                            FirstName = "Kim",
                            LastName = "Cartwright",
                            Phone = "86034255857",
                            Province = "South Carolina",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            AddressLine = "Suite 464",
                            City = "Hilariohaven",
                            Country = "Montenegro",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(4036),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1971, 8, 21, 7, 46, 3, 224, DateTimeKind.Local).AddTicks(4323),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cheryl_feest@gmail.com",
                            FirstName = "Cheryl",
                            LastName = "Feest",
                            Phone = "66970475245",
                            Province = "Kansas",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            AddressLine = "Suite 353",
                            City = "Port Dustytown",
                            Country = "Norway",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(4931),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1971, 12, 29, 10, 24, 45, 917, DateTimeKind.Local).AddTicks(7567),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jackie32@hotmail.com",
                            FirstName = "Jackie",
                            LastName = "Casper",
                            Phone = "55467656221",
                            Province = "Tennessee",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            AddressLine = "Suite 909",
                            City = "North Nashshire",
                            Country = "Burundi",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(5881),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1969, 11, 6, 22, 40, 49, 214, DateTimeKind.Local).AddTicks(3518),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cameron_becker50@hotmail.com",
                            FirstName = "Cameron",
                            LastName = "Becker",
                            Phone = "22292857626",
                            Province = "Alaska",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            AddressLine = "Suite 048",
                            City = "Ahmedshire",
                            Country = "Belarus",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(6779),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1998, 1, 5, 13, 15, 6, 480, DateTimeKind.Local).AddTicks(4171),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gerald.gorczany22@hotmail.com",
                            FirstName = "Gerald",
                            LastName = "Gorczany",
                            Phone = "50750236880",
                            Province = "Utah",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            AddressLine = "Apt. 087",
                            City = "Gusikowskifurt",
                            Country = "Palau",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(7758),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1960, 5, 23, 7, 8, 8, 253, DateTimeKind.Local).AddTicks(3859),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lyle67@hotmail.com",
                            FirstName = "Lyle",
                            LastName = "Huel",
                            Phone = "73062703535",
                            Province = "Illinois",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            AddressLine = "Suite 257",
                            City = "Selmerfort",
                            Country = "Slovenia",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(8683),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1971, 4, 25, 21, 36, 50, 192, DateTimeKind.Local).AddTicks(230),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dustin.bergnaum@gmail.com",
                            FirstName = "Dustin",
                            LastName = "Bergnaum",
                            Phone = "87848853306",
                            Province = "New Mexico",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            AddressLine = "Apt. 645",
                            City = "Lake Alysson",
                            Country = "Djibouti",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 188, DateTimeKind.Utc).AddTicks(9683),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1999, 7, 17, 0, 53, 39, 371, DateTimeKind.Local).AddTicks(9308),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shannon_abbott51@hotmail.com",
                            FirstName = "Shannon",
                            LastName = "Abbott",
                            Phone = "66559541913",
                            Province = "Texas",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            AddressLine = "Apt. 799",
                            City = "West Kariane",
                            Country = "Tokelau",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(599),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1964, 6, 17, 7, 14, 48, 421, DateTimeKind.Local).AddTicks(1395),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucia_bogisich@yahoo.com",
                            FirstName = "Lucia",
                            LastName = "Bogisich",
                            Phone = "47649602859",
                            Province = "Arkansas",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            AddressLine = "Apt. 553",
                            City = "Morissettemouth",
                            Country = "French Polynesia",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(1580),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1997, 10, 11, 0, 19, 31, 443, DateTimeKind.Local).AddTicks(6758),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carole.brown23@hotmail.com",
                            FirstName = "Carole",
                            LastName = "Brown",
                            Phone = "22480197110",
                            Province = "Colorado",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            AddressLine = "Suite 080",
                            City = "Emardmouth",
                            Country = "Madagascar",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(2435),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1998, 9, 7, 4, 0, 10, 872, DateTimeKind.Local).AddTicks(3243),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cory86@hotmail.com",
                            FirstName = "Cory",
                            LastName = "DuBuque",
                            Phone = "53844889875",
                            Province = "Texas",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            AddressLine = "Apt. 179",
                            City = "Wisozkton",
                            Country = "Yemen",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(3293),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1971, 12, 17, 2, 2, 3, 163, DateTimeKind.Local).AddTicks(764),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bennie_emard33@gmail.com",
                            FirstName = "Bennie",
                            LastName = "Emard",
                            Phone = "10702779484",
                            Province = "Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            AddressLine = "Apt. 139",
                            City = "South Casandraberg",
                            Country = "Saint Kitts and Nevi",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(4136),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1995, 4, 9, 22, 45, 23, 815, DateTimeKind.Local).AddTicks(4691),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rolando90@hotmail.com",
                            FirstName = "Rolando",
                            LastName = "Schumm",
                            Phone = "50344032704",
                            Province = "Minnesota",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            AddressLine = "Suite 539",
                            City = "New Lawson",
                            Country = "Martinique",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(5182),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1992, 3, 1, 1, 55, 7, 269, DateTimeKind.Local).AddTicks(6231),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "guillermo_reynolds@yahoo.com",
                            FirstName = "Guillermo",
                            LastName = "Reynolds",
                            Phone = "50184297867",
                            Province = "West Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            AddressLine = "Apt. 760",
                            City = "East Justinefort",
                            Country = "Germany",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(6100),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1983, 10, 31, 18, 56, 39, 368, DateTimeKind.Local).AddTicks(928),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jesse_baumbach62@yahoo.com",
                            FirstName = "Jesse",
                            LastName = "Baumbach",
                            Phone = "00048134210",
                            Province = "New Hampshire",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            AddressLine = "Apt. 732",
                            City = "East Augusta",
                            Country = "Andorra",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(7016),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1957, 7, 14, 13, 1, 21, 666, DateTimeKind.Local).AddTicks(2834),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sam35@gmail.com",
                            FirstName = "Sam",
                            LastName = "Casper",
                            Phone = "14557601441",
                            Province = "Florida",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            AddressLine = "Apt. 175",
                            City = "West Veda",
                            Country = "Montserrat",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(7990),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1980, 9, 3, 21, 5, 33, 503, DateTimeKind.Local).AddTicks(9818),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophie.nikolaus38@hotmail.com",
                            FirstName = "Sophie",
                            LastName = "Nikolaus",
                            Phone = "26303653577",
                            Province = "Minnesota",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            AddressLine = "Suite 928",
                            City = "West Wiley",
                            Country = "Russian Federation",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(8943),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1976, 8, 20, 23, 20, 15, 308, DateTimeKind.Local).AddTicks(1314),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marco73@hotmail.com",
                            FirstName = "Marco",
                            LastName = "Witting",
                            Phone = "14264747436",
                            Province = "New Hampshire",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            AddressLine = "Apt. 420",
                            City = "Johnsonfurt",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 189, DateTimeKind.Utc).AddTicks(9901),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1956, 10, 2, 10, 9, 5, 321, DateTimeKind.Local).AddTicks(7407),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chester_boyer48@yahoo.com",
                            FirstName = "Chester",
                            LastName = "Boyer",
                            Phone = "73081459720",
                            Province = "Oregon",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            AddressLine = "Suite 986",
                            City = "South Robb",
                            Country = "Gibraltar",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 190, DateTimeKind.Utc).AddTicks(790),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(2002, 7, 30, 4, 52, 15, 700, DateTimeKind.Local).AddTicks(6890),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nellie69@hotmail.com",
                            FirstName = "Nellie",
                            LastName = "Anderson",
                            Phone = "93699091653",
                            Province = "Washington",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            AddressLine = "Apt. 064",
                            City = "Lorinetown",
                            Country = "Solomon Islands",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 190, DateTimeKind.Utc).AddTicks(1745),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1990, 7, 15, 11, 34, 38, 701, DateTimeKind.Local).AddTicks(2294),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "philip4@hotmail.com",
                            FirstName = "Philip",
                            LastName = "Osinski",
                            Phone = "81846974876",
                            Province = "West Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            AddressLine = "Apt. 883",
                            City = "East Parkerville",
                            Country = "Lesotho",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 190, DateTimeKind.Utc).AddTicks(2624),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1975, 4, 5, 6, 32, 11, 603, DateTimeKind.Local).AddTicks(3845),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah_kutch@yahoo.com",
                            FirstName = "Noah",
                            LastName = "Kutch",
                            Phone = "63844817055",
                            Province = "Montana",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            AddressLine = "Suite 538",
                            City = "South Pansy",
                            Country = "Falkland Islands (Ma",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 190, DateTimeKind.Utc).AddTicks(3488),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1984, 1, 12, 10, 4, 39, 846, DateTimeKind.Local).AddTicks(6698),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "florence.langworth@yahoo.com",
                            FirstName = "Florence",
                            LastName = "Langworth",
                            Phone = "67525259046",
                            Province = "Iowa",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            AddressLine = "Suite 178",
                            City = "Feestchester",
                            Country = "Kazakhstan",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 190, DateTimeKind.Utc).AddTicks(4406),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1995, 2, 18, 10, 41, 20, 713, DateTimeKind.Local).AddTicks(611),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hugo.carroll83@gmail.com",
                            FirstName = "Hugo",
                            LastName = "Carroll",
                            Phone = "76287414986",
                            Province = "Washington",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            AddressLine = "Suite 099",
                            City = "Martyshire",
                            Country = "Serbia",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 54, 19, 190, DateTimeKind.Utc).AddTicks(5378),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(2002, 11, 22, 12, 50, 55, 942, DateTimeKind.Local).AddTicks(1321),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "moses.schneider@yahoo.com",
                            FirstName = "Moses",
                            LastName = "Schneider",
                            Phone = "56564087105",
                            Province = "Kentucky",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
