// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpraApi.Data;

#nullable disable

namespace SimpraApi.Data.Migrations
{
    [DbContext(typeof(SimpraDbContext))]
    partial class SimpraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpraApi.Domain.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Province")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LastName", "Country");

                    b.ToTable("Staff", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "9432 Bartoletti Turnpike",
                            City = "Haleyton",
                            Country = "French Southern Terr",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 568, DateTimeKind.Utc).AddTicks(1598),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1973, 8, 30, 6, 3, 20, 577, DateTimeKind.Local).AddTicks(9745),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Wallace92@yahoo.com",
                            FirstName = "Wallace",
                            LastName = "Hand",
                            Phone = "80237159147",
                            Province = "Mississippi",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "52257 Schuppe Flats",
                            City = "New Cassieberg",
                            Country = "Argentina",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 568, DateTimeKind.Utc).AddTicks(4027),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1974, 8, 1, 22, 53, 11, 807, DateTimeKind.Local).AddTicks(5573),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Greg_Carter@hotmail.com",
                            FirstName = "Greg",
                            LastName = "Carter",
                            Phone = "09382972750",
                            Province = "North Dakota",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "54272 Irving Mills",
                            City = "New Davionbury",
                            Country = "Indonesia",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 568, DateTimeKind.Utc).AddTicks(5114),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1990, 8, 9, 3, 7, 32, 964, DateTimeKind.Local).AddTicks(6452),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Olivia.Moore74@gmail.com",
                            FirstName = "Olivia",
                            LastName = "Moore",
                            Phone = "82876993655",
                            Province = "Ohio",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "24500 Annie Coves",
                            City = "West Antoinette",
                            Country = "Norfolk Island",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 568, DateTimeKind.Utc).AddTicks(6120),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1982, 1, 6, 20, 17, 30, 338, DateTimeKind.Local).AddTicks(1608),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Charlotte87@yahoo.com",
                            FirstName = "Charlotte",
                            LastName = "Yost",
                            Phone = "16258603097",
                            Province = "West Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "0292 Tillman Roads",
                            City = "New Vivianne",
                            Country = "Bangladesh",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 568, DateTimeKind.Utc).AddTicks(7255),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1965, 2, 25, 20, 4, 26, 314, DateTimeKind.Local).AddTicks(1205),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alexandra_Gleichner72@gmail.com",
                            FirstName = "Alexandra",
                            LastName = "Gleichner",
                            Phone = "72723911778",
                            Province = "Idaho",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AddressLine = "084 Glover Land",
                            City = "Gutmannside",
                            Country = "Lithuania",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 568, DateTimeKind.Utc).AddTicks(8322),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1974, 8, 19, 5, 32, 7, 978, DateTimeKind.Local).AddTicks(9003),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Peggy_Okuneva50@gmail.com",
                            FirstName = "Peggy",
                            LastName = "Okuneva",
                            Phone = "50261341380",
                            Province = "New Hampshire",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AddressLine = "58462 Smitham Meadow",
                            City = "Bertrammouth",
                            Country = "Antigua and Barbuda",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 568, DateTimeKind.Utc).AddTicks(9263),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1962, 5, 24, 13, 6, 29, 821, DateTimeKind.Local).AddTicks(6115),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jenna60@gmail.com",
                            FirstName = "Jenna",
                            LastName = "Mayer",
                            Phone = "94884512540",
                            Province = "New York",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AddressLine = "698 Kamren Unions",
                            City = "Port Abbyview",
                            Country = "Spain",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(221),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1967, 11, 30, 9, 32, 46, 689, DateTimeKind.Local).AddTicks(8799),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Patricia_Hackett57@hotmail.com",
                            FirstName = "Patricia",
                            LastName = "Hackett",
                            Phone = "55831909051",
                            Province = "Rhode Island",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AddressLine = "9751 Josefina Court",
                            City = "North Cecilshire",
                            Country = "Virgin Islands, U.S.",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(1317),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1984, 6, 18, 10, 0, 57, 728, DateTimeKind.Local).AddTicks(8425),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Wade2@gmail.com",
                            FirstName = "Wade",
                            LastName = "Stehr",
                            Phone = "38514456634",
                            Province = "Utah",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AddressLine = "34303 Katheryn Stream",
                            City = "Lake Trisha",
                            Country = "Spain",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(2387),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1994, 10, 19, 21, 3, 59, 11, DateTimeKind.Local).AddTicks(1978),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Roosevelt_Osinski82@hotmail.com",
                            FirstName = "Roosevelt",
                            LastName = "Osinski",
                            Phone = "91496976067",
                            Province = "Idaho",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AddressLine = "5950 Pasquale Heights",
                            City = "Lake Jennings",
                            Country = "United Arab Emirates",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(3362),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1986, 10, 21, 6, 54, 9, 179, DateTimeKind.Local).AddTicks(3857),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Johnny_Okuneva38@gmail.com",
                            FirstName = "Johnny",
                            LastName = "Okuneva",
                            Phone = "15452379403",
                            Province = "Maryland",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AddressLine = "8307 Jones Corners",
                            City = "Olafmouth",
                            Country = "Liberia",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(4347),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1995, 11, 6, 0, 54, 37, 177, DateTimeKind.Local).AddTicks(2812),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Marguerite_Wiza@gmail.com",
                            FirstName = "Marguerite",
                            LastName = "Wiza",
                            Phone = "20673377885",
                            Province = "Arkansas",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AddressLine = "322 Rosalee Lock",
                            City = "East Theresashire",
                            Country = "El Salvador",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(5304),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1980, 12, 27, 4, 40, 49, 933, DateTimeKind.Local).AddTicks(3644),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Carlton.Hirthe@gmail.com",
                            FirstName = "Carlton",
                            LastName = "Hirthe",
                            Phone = "49210859116",
                            Province = "California",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AddressLine = "761 Gutmann Cape",
                            City = "Danielchester",
                            Country = "Republic of Korea",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(6328),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1968, 1, 30, 16, 29, 14, 730, DateTimeKind.Local).AddTicks(7732),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lela_Anderson15@gmail.com",
                            FirstName = "Lela",
                            LastName = "Anderson",
                            Phone = "68298290896",
                            Province = "Connecticut",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AddressLine = "636 Stoltenberg Spur",
                            City = "Okunevafurt",
                            Country = "Paraguay",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(7305),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1976, 11, 24, 23, 19, 36, 83, DateTimeKind.Local).AddTicks(4276),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tyler_Larkin96@gmail.com",
                            FirstName = "Tyler",
                            LastName = "Larkin",
                            Phone = "46804185862",
                            Province = "Idaho",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AddressLine = "569 Corwin Plains",
                            City = "Douglasfurt",
                            Country = "Comoros",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(8355),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1972, 11, 11, 9, 19, 10, 944, DateTimeKind.Local).AddTicks(5642),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cornelius.Yost54@hotmail.com",
                            FirstName = "Cornelius",
                            LastName = "Yost",
                            Phone = "10280065681",
                            Province = "Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AddressLine = "60116 Littel Hills",
                            City = "New Afton",
                            Country = "Bulgaria",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 569, DateTimeKind.Utc).AddTicks(9305),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1964, 10, 26, 5, 10, 47, 148, DateTimeKind.Local).AddTicks(8010),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jared71@gmail.com",
                            FirstName = "Jared",
                            LastName = "Tremblay",
                            Phone = "46048189680",
                            Province = "Rhode Island",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AddressLine = "3643 Bogan Locks",
                            City = "West Garrick",
                            Country = "Guinea",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(243),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1982, 5, 19, 18, 1, 24, 12, DateTimeKind.Local).AddTicks(4972),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Monica_Dibbert51@yahoo.com",
                            FirstName = "Monica",
                            LastName = "Dibbert",
                            Phone = "14419937119",
                            Province = "Massachusetts",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AddressLine = "488 Ryan Knolls",
                            City = "South Else",
                            Country = "Wallis and Futuna",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(1299),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1960, 6, 25, 11, 30, 6, 190, DateTimeKind.Local).AddTicks(9277),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ricky77@yahoo.com",
                            FirstName = "Ricky",
                            LastName = "Mosciski",
                            Phone = "50024870797",
                            Province = "Vermont",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AddressLine = "0454 Bennett Avenue",
                            City = "Brendonmouth",
                            Country = "Guam",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(2404),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1960, 2, 22, 0, 16, 55, 672, DateTimeKind.Local).AddTicks(1714),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Casey.Okuneva@hotmail.com",
                            FirstName = "Casey",
                            LastName = "Okuneva",
                            Phone = "17758578287",
                            Province = "Michigan",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            AddressLine = "5700 Muller Roads",
                            City = "North Nameshire",
                            Country = "Mozambique",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(3361),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1973, 6, 1, 7, 43, 54, 775, DateTimeKind.Local).AddTicks(8286),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Timothy_Bogisich@gmail.com",
                            FirstName = "Timothy",
                            LastName = "Bogisich",
                            Phone = "23366717486",
                            Province = "Connecticut",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            AddressLine = "8477 Sporer Branch",
                            City = "Kozeyport",
                            Country = "Fiji",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(4363),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1965, 5, 23, 7, 20, 45, 212, DateTimeKind.Local).AddTicks(6140),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Merle_Stehr10@yahoo.com",
                            FirstName = "Merle",
                            LastName = "Stehr",
                            Phone = "68052897220",
                            Province = "Louisiana",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            AddressLine = "88410 Mann Manor",
                            City = "South Lisahaven",
                            Country = "Mali",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(5417),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1993, 7, 5, 20, 14, 22, 870, DateTimeKind.Local).AddTicks(2011),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Victor.Miller91@gmail.com",
                            FirstName = "Victor",
                            LastName = "Miller",
                            Phone = "45164357514",
                            Province = "Wisconsin",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            AddressLine = "39193 Jasper Alley",
                            City = "Sofiafort",
                            Country = "Venezuela",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(6409),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(2002, 9, 30, 12, 2, 30, 602, DateTimeKind.Local).AddTicks(7908),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Courtney_Fahey@hotmail.com",
                            FirstName = "Courtney",
                            LastName = "Fahey",
                            Phone = "64549537617",
                            Province = "Iowa",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            AddressLine = "8794 Ken Rue",
                            City = "Lake Walker",
                            Country = "San Marino",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(7339),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1974, 4, 4, 11, 8, 56, 813, DateTimeKind.Local).AddTicks(7540),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hector22@yahoo.com",
                            FirstName = "Hector",
                            LastName = "Kutch",
                            Phone = "65618952499",
                            Province = "Delaware",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            AddressLine = "34000 Tod Port",
                            City = "Clydeport",
                            Country = "Bouvet Island (Bouve",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(8405),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1998, 7, 31, 22, 49, 40, 605, DateTimeKind.Local).AddTicks(2778),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Patti_Gorczany2@yahoo.com",
                            FirstName = "Patti",
                            LastName = "Gorczany",
                            Phone = "44185912803",
                            Province = "New Hampshire",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            AddressLine = "615 Antone Cliffs",
                            City = "Arahaven",
                            Country = "Philippines",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 570, DateTimeKind.Utc).AddTicks(9382),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1964, 9, 2, 14, 49, 26, 784, DateTimeKind.Local).AddTicks(7546),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jack_Stamm@yahoo.com",
                            FirstName = "Jack",
                            LastName = "Stamm",
                            Phone = "94334149629",
                            Province = "Colorado",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            AddressLine = "0267 Bogan Hill",
                            City = "Gottliebtown",
                            Country = "Benin",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 571, DateTimeKind.Utc).AddTicks(336),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1974, 4, 22, 0, 11, 7, 414, DateTimeKind.Local).AddTicks(380),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Omar_Kovacek75@yahoo.com",
                            FirstName = "Omar",
                            LastName = "Kovacek",
                            Phone = "32955742022",
                            Province = "Louisiana",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            AddressLine = "51770 Lebsack Tunnel",
                            City = "South Kellichester",
                            Country = "Rwanda",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 571, DateTimeKind.Utc).AddTicks(1257),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1957, 6, 23, 18, 0, 26, 758, DateTimeKind.Local).AddTicks(574),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rosemarie21@yahoo.com",
                            FirstName = "Rosemarie",
                            LastName = "Boehm",
                            Phone = "23220637979",
                            Province = "Ohio",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            AddressLine = "3510 Lavada Parkway",
                            City = "Carleyland",
                            Country = "Latvia",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 571, DateTimeKind.Utc).AddTicks(2425),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1982, 2, 3, 6, 45, 9, 960, DateTimeKind.Local).AddTicks(5189),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Muriel_Klocko@hotmail.com",
                            FirstName = "Muriel",
                            LastName = "Klocko",
                            Phone = "09131372062",
                            Province = "North Dakota",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            AddressLine = "186 Crist Shore",
                            City = "New Eduardo",
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 571, DateTimeKind.Utc).AddTicks(4300),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1991, 4, 1, 23, 52, 44, 565, DateTimeKind.Local).AddTicks(7759),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "May.Beatty@yahoo.com",
                            FirstName = "May",
                            LastName = "Beatty",
                            Phone = "66369985756",
                            Province = "Vermont",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            AddressLine = "55030 Omer Meadow",
                            City = "South Rettabury",
                            Country = "United Arab Emirates",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 571, DateTimeKind.Utc).AddTicks(7255),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1975, 11, 21, 2, 10, 31, 781, DateTimeKind.Local).AddTicks(6286),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Heidi.Moore@gmail.com",
                            FirstName = "Heidi",
                            LastName = "Moore",
                            Phone = "92167107742",
                            Province = "New Hampshire",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            AddressLine = "89876 Camila Trace",
                            City = "Lake Leonard",
                            Country = "Uruguay",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 571, DateTimeKind.Utc).AddTicks(8724),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1988, 3, 14, 8, 29, 11, 795, DateTimeKind.Local).AddTicks(4860),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "June_Jacobson62@yahoo.com",
                            FirstName = "June",
                            LastName = "Jacobson",
                            Phone = "80974393988",
                            Province = "Texas",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            AddressLine = "0022 Milan Walk",
                            City = "Lake Caleb",
                            Country = "Trinidad and Tobago",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(41),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1961, 4, 12, 1, 23, 13, 325, DateTimeKind.Local).AddTicks(4776),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brent_Turner@gmail.com",
                            FirstName = "Brent",
                            LastName = "Turner",
                            Phone = "64412220714",
                            Province = "North Carolina",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            AddressLine = "1626 Oral Fork",
                            City = "Port Kaylahmouth",
                            Country = "Zimbabwe",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(1044),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1953, 5, 30, 5, 44, 52, 730, DateTimeKind.Local).AddTicks(7965),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Abel_Mohr@gmail.com",
                            FirstName = "Abel",
                            LastName = "Mohr",
                            Phone = "82825327807",
                            Province = "West Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            AddressLine = "074 Rutherford Stravenue",
                            City = "Eliseport",
                            Country = "Nicaragua",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(2025),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1961, 8, 15, 22, 33, 27, 994, DateTimeKind.Local).AddTicks(2449),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Antonia.Kris@yahoo.com",
                            FirstName = "Antonia",
                            LastName = "Kris",
                            Phone = "50767393873",
                            Province = "North Dakota",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            AddressLine = "8325 Schmidt Trail",
                            City = "New Annabellemouth",
                            Country = "Albania",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(3004),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(2001, 10, 27, 13, 32, 20, 387, DateTimeKind.Local).AddTicks(8559),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lora.Haag@yahoo.com",
                            FirstName = "Lora",
                            LastName = "Haag",
                            Phone = "77019889112",
                            Province = "Arizona",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            AddressLine = "8300 Ray Island",
                            City = "South Selena",
                            Country = "Saint Barthelemy",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(4017),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1987, 11, 13, 7, 1, 13, 777, DateTimeKind.Local).AddTicks(7511),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Violet44@hotmail.com",
                            FirstName = "Violet",
                            LastName = "Gleason",
                            Phone = "11333755473",
                            Province = "Ohio",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            AddressLine = "0002 Nader Courts",
                            City = "North Desmondberg",
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(4962),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1956, 11, 27, 6, 31, 20, 782, DateTimeKind.Local).AddTicks(112),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Denise54@yahoo.com",
                            FirstName = "Denise",
                            LastName = "Reichert",
                            Phone = "00860581757",
                            Province = "Alabama",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            AddressLine = "6585 Hosea Lakes",
                            City = "Alvenaton",
                            Country = "Kenya",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(6034),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1960, 8, 22, 1, 14, 5, 972, DateTimeKind.Local).AddTicks(6493),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Todd_Hyatt38@yahoo.com",
                            FirstName = "Todd",
                            LastName = "Hyatt",
                            Phone = "39945195666",
                            Province = "Montana",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            AddressLine = "0510 Cedrick Circles",
                            City = "West Esteban",
                            Country = "Ghana",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(7106),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1960, 12, 1, 11, 40, 11, 173, DateTimeKind.Local).AddTicks(7473),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Stanley_Haag69@gmail.com",
                            FirstName = "Stanley",
                            LastName = "Haag",
                            Phone = "22292275202",
                            Province = "Maine",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            AddressLine = "2441 Mertz Glens",
                            City = "Gleasonchester",
                            Country = "Reunion",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(8027),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1975, 4, 27, 15, 43, 36, 356, DateTimeKind.Local).AddTicks(9960),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jackie_Jast@yahoo.com",
                            FirstName = "Jackie",
                            LastName = "Jast",
                            Phone = "88320955701",
                            Province = "Illinois",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            AddressLine = "886 Heber Branch",
                            City = "West Eden",
                            Country = "Mali",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(8964),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1984, 3, 5, 11, 20, 3, 462, DateTimeKind.Local).AddTicks(664),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cassandra_Fay@hotmail.com",
                            FirstName = "Cassandra",
                            LastName = "Fay",
                            Phone = "37580793782",
                            Province = "South Carolina",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            AddressLine = "804 Nathaniel Port",
                            City = "Stephenbury",
                            Country = "Cuba",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 572, DateTimeKind.Utc).AddTicks(9974),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1963, 7, 7, 15, 31, 11, 223, DateTimeKind.Local).AddTicks(8090),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maxine94@gmail.com",
                            FirstName = "Maxine",
                            LastName = "Trantow",
                            Phone = "04937879270",
                            Province = "New York",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            AddressLine = "1018 Schumm Brook",
                            City = "Jaquelinmouth",
                            Country = "Serbia",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 573, DateTimeKind.Utc).AddTicks(1009),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1956, 12, 7, 17, 15, 53, 538, DateTimeKind.Local).AddTicks(1641),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Paul39@gmail.com",
                            FirstName = "Paul",
                            LastName = "Dibbert",
                            Phone = "04439540595",
                            Province = "Massachusetts",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            AddressLine = "769 Zboncak Ridges",
                            City = "North Salvador",
                            Country = "United Arab Emirates",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 573, DateTimeKind.Utc).AddTicks(2016),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1968, 3, 25, 2, 38, 38, 587, DateTimeKind.Local).AddTicks(3665),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Vivian_Hills12@gmail.com",
                            FirstName = "Vivian",
                            LastName = "Hills",
                            Phone = "76593850235",
                            Province = "Alabama",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            AddressLine = "864 Audreanne Parkway",
                            City = "Parisland",
                            Country = "Burundi",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 573, DateTimeKind.Utc).AddTicks(3014),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1955, 6, 5, 3, 34, 40, 585, DateTimeKind.Local).AddTicks(6587),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ginger.Gottlieb@hotmail.com",
                            FirstName = "Ginger",
                            LastName = "Gottlieb",
                            Phone = "12146180560",
                            Province = "Idaho",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            AddressLine = "4559 Reina Extensions",
                            City = "West Corene",
                            Country = "Iraq",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 573, DateTimeKind.Utc).AddTicks(3959),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1953, 11, 22, 13, 13, 20, 367, DateTimeKind.Local).AddTicks(215),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Stanley_Gaylord@hotmail.com",
                            FirstName = "Stanley",
                            LastName = "Gaylord",
                            Phone = "09935440484",
                            Province = "Arkansas",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            AddressLine = "0998 Gilbert Islands",
                            City = "Kesslerchester",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 573, DateTimeKind.Utc).AddTicks(5032),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1996, 1, 24, 3, 21, 56, 600, DateTimeKind.Local).AddTicks(9038),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Clinton.Leannon80@hotmail.com",
                            FirstName = "Clinton",
                            LastName = "Leannon",
                            Phone = "51847379146",
                            Province = "Idaho",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            AddressLine = "437 Rubie Greens",
                            City = "Kaitlynborough",
                            Country = "Cote d'Ivoire",
                            CreatedAt = new DateTime(2023, 5, 11, 13, 11, 18, 573, DateTimeKind.Utc).AddTicks(5992),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1972, 5, 16, 18, 54, 58, 421, DateTimeKind.Local).AddTicks(3398),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kristi_Fisher44@gmail.com",
                            FirstName = "Kristi",
                            LastName = "Fisher",
                            Phone = "34858194076",
                            Province = "Georgia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
